[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py *_test.py *.spec.py
python_classes = Test*
python_functions = test_*
addopts = --verbose
markers =
    asyncio: marks tests as async (deselect with '-m "not asyncio"')
